# Generated by Django 5.2.15 on 2026-06-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='available',
            new_name='availability_status',
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
