# Generated by Django 5.2.15 on 2026-06-18 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('trainers', '0002_rename_available_trainer_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.trainer'),
        ),
    ]
